### ISSUE TITLE
缺少mutagan库

### ISSUE THREAD

**Issue by Venarys** [crmmc/Ncm2Music#1]
我运行的时候发现过不了，可能还要加个这个库
_pip install mutagen_

**Comment by crmmc** [comment]
发现我的readme写的有点乱，readme其实是告诉了这个库的需要的，我改改就好
建议用我的新项目 nqdump，那个效率更高，而且支持多线程，能充分利用CPU性能，速度比这个python版本快不少
而且同样支持ncm和部分QQ音乐文件

**Comment by crmmc** [comment]
新项目地址： https://github.com/crmmc/nqdumpgo
带有windows与Linux平台的release
